### ISSUE TITLE
npm installに時間がかかる

### ISSUE THREAD

**Issue by gulping** [coa00/pizas#1]
`@babel/core`などを`dependencies`に持つためinstallに時間がかかりました。

おそらく@babel/preset-env, babel-loader, webpackは*dev*Dependenciesに移動すると解決するように思います。
(逆に、detect-passive-eventsはdevDependenciesでなくdependenciesが適切なように思います)

**Comment by coa00** [comment]
@gulping package.json の設定の見直しと npm  の対象ファイルを減らしました。
